<Project>
    <PropertyGroup>
        <AutomateLocalDeployment>false</AutomateLocalDeployment>

        <!-- MelonLoader assemblies (net6) -->
        <MelonLoaderAssembliesPath>..\ScheduleOneAssemblies\MelonLoader</MelonLoaderAssembliesPath>

        <!-- Il2Cpp game assemblies -->
        <Il2CppAssembliesPath>..\ScheduleOneAssemblies\Il2CppAssemblies</Il2CppAssembliesPath>

        <!-- Local Il2Cpp deployment path -->
        <LocalIl2CppDeploymentPath>null</LocalIl2CppDeploymentPath>
    </PropertyGroup>
</Project>
