<Project Sdk="Microsoft.NET.Sdk">
    <!-- Imports the standard GitHub build properties. -->
    <Import Project="../github.build.props" Condition="Exists('../github.build.props')" />

    <!-- Imports any local build properties over the GitHub repository one. -->
    <Import Project="../local.build.props" Condition="Exists('../local.build.props')" />

    <!-- Imports CI build properties for GitHub Actions -->
    <Import Project="../ci.build.props" Condition="Exists('../ci.build.props')" />

    <!-- General properties -->
    <PropertyGroup>
        <Authors>ifBars</Authors>
        <PackageId>S1API.Forked</PackageId>
        <Description>A Schedule One Mono / Il2Cpp Cross Compatibility Layer (Forked from the original S1API by Kabooma)</Description>
        <RepositoryUrl>https://github.com/ifBars/S1API</RepositoryUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <Nullable>enable</Nullable>
        <Configurations>MonoMelon;Il2CppMelon</Configurations>
        <Platforms>AnyCPU</Platforms>
        <RootNamespace>S1API</RootNamespace>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591</NoWarn>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <LangVersion>latest</LangVersion>
        <Version>3.1.15</Version>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'MonoMelon'">
        <TargetFramework>netstandard2.1</TargetFramework>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Il2CppMelon'">
        <TargetFramework>net6.0</TargetFramework>
    </PropertyGroup>

    <!-- IL2CPP Specific Deps -->
    <ItemGroup Condition="'$(Configuration)' == 'Il2CppMelon'">
        <Reference Include="$(MelonLoaderAssembliesPath)\Il2CppInterop.Runtime.dll" />
        <Reference Include="$(MelonLoaderAssembliesPath)\Il2CppInterop.Common.dll" />
        <Reference Include="$(MelonLoaderAssembliesPath)\Il2CppInterop.HarmonySupport.dll" />
        <Reference Include="$(MelonLoaderAssembliesPath)\Il2CppInterop.Generator.dll" />
        <Reference Include="$(MelonLoaderAssembliesPath)\UnityEngine.Il2CppAssetBundleManager.dll" />

        <Reference Include="$(Il2CppAssembliesPath)\Assembly-CSharp.dll" />
        <Reference Include="Il2CppScheduleOne.Core">
            <HintPath>$(Il2CppAssembliesPath)\Il2CppScheduleOne.Core.dll</HintPath>
        </Reference>
        <Reference Include="$(Il2CppAssembliesPath)\Il2Cppmscorlib.dll" />
        <Reference Include="$(Il2CppAssembliesPath)\UnityEngine.dll" />
        <Reference Include="$(Il2CppAssembliesPath)\UnityEngine.CoreModule.dll" />
        <Reference Include="$(Il2CppAssembliesPath)\UnityEngine.AnimationModule.dll" />
        <Reference Include="$(Il2CppAssembliesPath)\UnityEngine.UI.dll" />
        <Reference Include="$(Il2CppAssembliesPath)\UnityEngine.InputLegacyModule.dll" />
        <Reference Include="$(Il2CppAssembliesPath)\UnityEngine.IMGUIModule.dll" />
        <Reference Include="$(Il2CppAssembliesPath)\UnityEngine.UIModule.dll" />
        <Reference Include="$(Il2CppAssembliesPath)\UnityEngine.JSONSerializeModule.dll" />
        <Reference Include="$(Il2CppAssembliesPath)\UnityEngine.TextRenderingModule.dll" />
        <Reference Include="$(Il2CppAssembliesPath)\UnityEngine.ImageConversionModule.dll" />
        <Reference Include="$(Il2CppAssembliesPath)\UnityEngine.PhysicsModule.dll" />
        <Reference Include="$(Il2CppAssembliesPath)\Unity.TextMeshPro.dll" />
        <Reference Include="$(Il2CppAssembliesPath)\UnityEngine.AIModule.dll" />

        <Reference Include="$(Il2CppAssembliesPath)\Il2CppFishNet.Runtime.dll" />
    </ItemGroup>

    <!-- Mono Specific Deps -->
    <ItemGroup Condition="'$(Configuration)' == 'MonoMelon'">
        <!--<Reference Include="Assembly-CSharp" Publicize="true">
            <HintPath>$(MonoAssembliesPath)/Assembly-CSharp.dll</HintPath>
        </Reference> -->
        <Reference Include="Assembly-CSharp">
            <HintPath>$(MonoAssembliesPath)/Assembly-CSharp.dll</HintPath>
        </Reference>
        <Reference Include="ScheduleOne.Core">
            <HintPath>$(MonoAssembliesPath)/ScheduleOne.Core.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine">
            <HintPath>$(MonoAssembliesPath)/UnityEngine.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.CoreModule">
            <HintPath>$(MonoAssembliesPath)/UnityEngine.CoreModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.AnimationModule">
            <HintPath>$(MonoAssembliesPath)/UnityEngine.AnimationModule.dll</HintPath>
        </Reference>
        <Reference Include="FishNet.Runtime">
            <HintPath>$(MonoAssembliesPath)/FishNet.Runtime.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UI">
            <HintPath>$(MonoAssembliesPath)/UnityEngine.UI.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.InputLegacyModule">
            <HintPath>$(MonoAssembliesPath)/UnityEngine.InputLegacyModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.IMGUIModule">
            <HintPath>$(MonoAssembliesPath)/UnityEngine.IMGUIModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.AssetBundleModule">
            <HintPath>$(MonoAssembliesPath)/UnityEngine.AssetBundleModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UIModule">
            <HintPath>$(MonoAssembliesPath)/UnityEngine.UIModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.JSONSerializeModule">
            <HintPath>$(MonoAssembliesPath)/UnityEngine.JSONSerializeModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.TextRenderingModule">
            <HintPath>$(MonoAssembliesPath)/UnityEngine.TextRenderingModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ImageConversionModule">
            <HintPath>$(MonoAssembliesPath)/UnityEngine.ImageConversionModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.PhysicsModule">
            <HintPath>$(MonoAssembliesPath)/UnityEngine.PhysicsModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.AIModule">
            <HintPath>$(MonoAssembliesPath)/UnityEngine.AIModule.dll</HintPath>
        </Reference>
        <Reference Include="Unity.TextMeshPro">
            <HintPath>$(MonoAssembliesPath)/Unity.TextMeshPro.dll</HintPath>
        </Reference>
    </ItemGroup>

    <!-- Melon Deps -->
    <!-- MonoMelon uses net35, Il2CppMelon uses net6 -->
    <ItemGroup Condition="'$(Configuration)' == 'MonoMelon'">
        <Reference Include="0Harmony">
            <HintPath>$(MelonLoaderMonoAssembliesPath)/0Harmony.dll</HintPath>
        </Reference>
        <Reference Include="MelonLoader">
            <HintPath>$(MelonLoaderMonoAssembliesPath)/MelonLoader.dll</HintPath>
        </Reference>
    </ItemGroup>
    
    <ItemGroup Condition="'$(Configuration)' == 'Il2CppMelon'">
        <Reference Include="0Harmony">
            <HintPath>$(MelonLoaderAssembliesPath)/0Harmony.dll</HintPath>
        </Reference>
        <Reference Include="MelonLoader">
            <HintPath>$(MelonLoaderAssembliesPath)/MelonLoader.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="api\**" />
      <Compile Remove="docs\**" />
      <Compile Remove="templates\**" />
      <Compile Remove="_site\**" />
      <EmbeddedResource Remove="api\**" />
      <EmbeddedResource Remove="docs\**" />
      <EmbeddedResource Remove="templates\**" />
      <EmbeddedResource Remove="_site\**" />
      <None Remove="api\**" />
      <None Remove="docs\**" />
      <None Remove="templates\**" />
      <None Remove="_site\**" />
    </ItemGroup>
    <ItemGroup>
      <None Remove="toc.yml" />
    </ItemGroup>

    <!-- Shared Deps -->
    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
    </ItemGroup>

    <!-- Automated local deployment -->
    <Target Name="PostBuildIl2CppMelon" AfterTargets="Build" Condition="'$(AutomateLocalDeployment)' == 'true' and '$(Configuration)' == 'Il2CppMelon'">
        <Message Text="[IL2CPP/MelonLoader] Deploying S1API to local Il2Cpp mods folder" Importance="high" />
        <Copy SourceFiles=".\bin\Il2CppMelon\net6.0\S1API.dll" DestinationFiles="$(LocalIl2CppDeploymentPath)\Mods\S1API.Il2Cpp.MelonLoader.dll" />
    </Target>

    <Target Name="PostBuildMonoMelon" AfterTargets="Build" Condition="'$(AutomateLocalDeployment)' == 'true' and '$(Configuration)' == 'MonoMelon'">
        <Message Text="[Mono/MelonLoader] Deploying S1API to local Mono mods folder" Importance="high" />
        <Copy SourceFiles=".\bin\MonoMelon\netstandard2.1\S1API.dll" DestinationFiles="$(LocalMonoDeploymentPath)\Mods\S1API.Mono.MelonLoader.dll" />
    </Target>

</Project>
